=== svenwltr/apache2-config-generator/src/main/xsd/apache-config-gen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:eu.wltr.a2cg" xmlns:tns="urn:eu.wltr.a2cg" elementFormDefault="qualified">

    <element name="config" type="tns:configuration"></element>
    
    <complexType name="configuration">
    	<sequence>
    		<element name="host" type="tns:virtualHost" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="virtualHost">
    	<sequence>
    		<element name="name" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="alias" maxOccurs="unbounded" minOccurs="0"
    			type="tns:serverAlias">
    		</element>
    		<choice maxOccurs="1" minOccurs="1">
    			<element name="proxy" type="string"></element>
    			<element name="static" type="tns:static"></element>

    			<element name="php" type="string"></element>
    			<element name="wsgi" type="string"></element>
    		</choice>
    		<element name="location" type="tns:location" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    <complexType name="serverAlias">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="redirect" type="boolean"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="static">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="dav" type="boolean"></attribute>
    			<attribute name="index" type="boolean"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="NewComplexType"></complexType>

    <complexType name="location">
    	<sequence>
    		<element name="location" type="tns:location"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<choice>
    			<element name="static" type="tns:static"></element>
    		</choice>
    	</sequence>
    	<attribute name="path" type="string"></attribute>
    </complexType>
</schema>

=== svenwltr/apache2-config-generator/src/test/resources/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="urn:eu.wltr.a2cg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:eu.wltr.a2cg ../../main/xsd/apache-config-gen.xsd">
	<host>
		<name>www.gh.example.com</name>
		<alias redirect="true">gh.example.com</alias>
		<proxy>http://www.github.org/</proxy>
	</host>

	<host>
		<name>www.ls.example.com</name>
		<alias>ls.example.com</alias>
		<static>/var/www/ls.example.com/</static>
	</host>

	<host>
		<name>dav.example.com</name>
		<static dav="true">/var/www/dav.example.com/</static>
	</host>

	<host>
		<name>php.example.com</name>
		<php>/var/www/php.example.com/</php>
	</host>

	<host>
		<name>wsgi.example.com</name>
		<wsgi>/var/www/wsgi.example.com/website.wsgi</wsgi>
		<location path="/static/">
			<static>/var/www/wsgi.example.com/static/</static>
		</location>
	</host>
</config>
